### PR TITLE
Create AVAILABLE_COMMANDS.md

### PR DESCRIPTION
**Pull request by pahosler**
please review for merge

### CODE REVIEW

**Comment by pahosler** [comment]
let's just get this file added, changes/additions can be made in github via edit.

**Comment by jodylecompte** [comment]
@joker314 Let's make the corrections in #70 so that way both corrections to grammar are in one commit and file addition is separate.

**Comment by pahosler** [comment]
@joker314 it's very easy to edit text files in github without downloading them and editing locally. Just select the file and then select edit. After changes are made you can either submit as a PR or do it without a PR. I used a PR this time because it is adding files to the master branch. Going forward we shouldn't need a PR to edit the file unless the person editing is making some significant changes, like redoing the entire content or reformatting the document in some way. Simply adding a command to the document shouldn't require a PR as long as the currently established format is adhered to.

**Comment by joker314** [comment]
The point is that if you change the code, you always have to change the markdown file.  These changes should, of course, be included as commits in the pull requests that change the wording (note, we should never push to master without two approvals, no matter how trivial a change?). However, it could save some effort if a command line tool added the second change for you.

**Comment by pahosler** [comment]
Documentation isn't code that affects the operation of the bot. 

you are wanting to approve from the command line? You can do it, but it's more complicated and I'm not sure it's scriptable. I know it's conceivable that some people don't have their browser open all the time...
In a nutshell, if you add something to the md files, make sure you know what you are doing and follow the current format. Conversely we could have roles, i.e. people that are maintainers of docs etc. which isn't a horrible idea in my opinion

**Comment by joker314** [comment]
I'm not wanting to approve from the command line.

I want a tool (like a command "build docs") that I can run in the command line. This will scan all the command descriptions for changes, and reflect those changes in the docs file too. *shrugs*

**Pull request merged**
