### PR TITLE
Add dice command

### LINKED ISSUE #61: Dice Roll Command
Whether for legit table topping or just for lols, a dice roller should be added to the bot.

It should accept a string of dice and rolls in the following format: "1d6 2d20" where the first number is the number or rolls and the second is the number of sides on the dice.

Example:
+rollit 1d6 2d20

Example Output:
Roll Total: 30
1d6:  1
1d20: 12
1d20: 17

### PR DESCRIPTION
**Pull request by glynnw**
Fixes #61

### CODE REVIEW

**Comment by jodylecompte** [comment]
@glynnw @pahosler 
This looks good, but let's not close out #61 yet as this doesn't have the DND / Pathfinder aspect described in #61. THis one is named dice, and we could name the DND dice roll.

**Comment by pahosler** [comment]
@jodylecompte maybe we could go ahead and merge, then one of us can update the feature in another pull request? Or have this as more of a generic random number generator and make another D&D dice roller? I'd be willing to make the changes or new roller unless you or Glen would prefer to.

**Comment by glynnw** [comment]
Also about the 5d6, while probably easy to implement, would come at the expense of validating that it is a correct type the issuer supplied to the command. I don't have any knowledge of board games like that so I assumed you could just increase the roll size to represent the random range of numbers increased die would have. So say you have 4, 6 sided dice, then you'd just do 1-24 or something.

Instead of formatting it 5d6, would it not make more sense to do the query response default that commando is built around and ask how many dice as another parameter? Or is that something extremely obvious for board games I don't see here?

**Comment by glynnw** [comment]
I'm going to just keep the current dice as a roll command and extend it to account for dice correctly in another command called dice. So essentially I'm going to create a roll and a dice command. That way this one doesn't roll 1 on two dice where it would instead be 2 as the lowest number possible.

**Comment by joker314** [comment]
@glynnw So you've decided that this PR is good, and then we can add a separate command later?

**Comment by glynnw** [comment]
No do not merge this one yet. I've got to add some functionality to the command first.

**Comment by glynnw** [comment]
I'll reopen this one when I've finished the command.

**Pull request closed without merging**
